var servers4Port = ["lexo-corp",
                    "global-pharm",
                    "snap-fitness",
                    "alpha-ent",
                    "aevum-police",
                    "unitalife",
                    "zb-def",
                    "univ-energy",
                    "nova-med"]

for (var i = 0; i < servers4Port.length; ++i) {
    var serv = servers4Port[i];

    killall(serv);
    run("cp-this.script",1,serv)
    //scp("omega-home.script", serv);
    brutessh(serv);
    ftpcrack(serv);
    relaysmtp(serv);
    httpworm(serv);
    nuke(serv);
    for (var j = 0; j < 30; ++j) {
        exec("target-weaken.script", serv,1,"the-hub",j);
    }
}