var servers3Port = ["summit-uni",
                    "catalyst",
                    "millenium-fitness",
                    "comptek",
                    "rothman-uni",
                    "I.I.I.I",
                    "rho-construction",
                    "netlink"];

for (var i = 0; i < servers3Port.length; ++i) {
    var serv = servers3Port[i];

    killall(serv);
    run("cp-this.script",1,serv)
    //scp("omega-home.script", serv);
    brutessh(serv);
    ftpcrack(serv);
    relaysmtp(serv);
    //httpworm(serv);
    nuke(serv);
    for (var j = 0; j < 8; ++j) {
        exec("target-weaken.script", serv,1,"neo-net",j);
    }
}